---
production:
  cmf: opennebula
  ca_path: '/etc/grid-security/certificates'
  insecure: false
  debug: false

development:
  cmf: opennebula
  ca_path: '/etc/grid-security/certificates'
  insecure: true
  debug: true

test:
  cmf: dummy
  ca_path: '/etc/grid-security/certificates'
  insecure: true
  debug: true
